# AutoGrad
I will be following this tutorial:
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

provides automatic differentiation for all ops on tensors
define by run framework - every iter can be different

In [1]:
import torch

In [4]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [14]:
print(y.grad_fn)

In [15]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [16]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


## Gradients
brackpropagate using out.backward()

In [17]:
out.backward()

In [18]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
